In [12]:
 import numpy as np #numpy kütüphanesini np olarak yazar
dizi= np.array([1,2,3,4,5])#numpy kütüphanesini oluşturmak için kullanılır

In [13]:
dizi

array([1, 2, 3, 4, 5])

In [14]:
dizi=a=np.array([1,2,3]) #np dizisinde atama yapmak için kullanılır
dizi

array([1, 2, 3])

In [15]:
 dizi=np.array([1,2,3,3.14]) # NumPy dizilerinin avantajı içindeki verilere göre kendisini tek tip olarak ayarlamasıdır
dizi

array([1.  , 2.  , 3.  , 3.14])

In [16]:
 dizi=np.array([1,2,3,3.14],dtype=int) # NumPy dizilerini tanımlama sırasında dizideki tüm elemanları tek tipe dönüştürme işlemi gerçekleştirebilir
 dizi

array([1, 2, 3, 3])

In [17]:
 birboyut=np.array([1,2,3]) # NumPy kütüphanesini import ettikten sonra aşağıdaki kodları yazarak bir boyutlu dizi oluşturur
birboyut

array([1, 2, 3])

In [18]:
 ikiboyut = np.array([[1,2,3], [4,5,6]]) # İki boyutlu dizi oluşturmak için aşağıdaki kodlamaları yapar
ikiboyut

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
ucboyut= np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]]) # Üç boyutlu dizi oluşturmak için aşağıdaki kodlamaları yapar
ucboyut