**numpy dizi işlemleri**

In [12]:
import numpy as np #numpy kütüphanesini np takma adı ile projeye dahil ediyoruz

In [14]:
dizi=np.full((4,3),5)#4(satır),3(sütündan) ve 5 içindeki şeyi gösterir
dizi

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [16]:
#yeni bir numpy dizisi oluşturuyoruz
np.array([1,2,3])

array([1, 2, 3])

In [21]:
#oluşturduğumuz diziyi bir değişkene aktarıyoruz
dizi=np.array(["elma","erik","iğde"])
dizi

array(['elma', 'erik', 'iğde'], dtype='<U4')

In [ ]:
dizi=np.array([1,2,3])

In [ ]:
dizi=np.array([1,2,3,14])

In [ ]:
dizi=dtype #dizinin değişken türünü verir.numpy dizilerinde elemanların hepsi aynı türdendir

In [ ]:
dtype('float64')

In [ ]:
dizi=np.array([1,2,3,14]), dtype=int

**numpy ile farklı boyutlarda dizi oluşturma**

In [32]:
#bir boyutlu dizi oluşturma
birboyut=np.array([1,2,3,4])
#iki boyutlu dizi oluşturma
ikiboyut=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [30]:
birboyut

array([1, 2, 3, 4])

In [34]:
ikiboyut

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**numpy yer tutucular**

In [37]:
np.zeros(7) #7 sıfırdan oluşan tek boyutlu dizi oluşturur

array([0., 0., 0., 0., 0., 0., 0.])

In [39]:
np.zeros((2,3),dtype=int) #sıfırdan oluşan 2 boyutlu int dizi oluşturur

array([[0, 0, 0],
       [0, 0, 0]])

In [41]:
np.ones(3)

array([1., 1., 1.])

In [43]:
np.full((4,3),5) #5 sayısından oluşan 2*3 dizi

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [45]:
np.arange(2,22,5)#başlangıçbitiş ve artış değerine göre dizi oluşturur

array([ 2,  7, 12, 17])

In [47]:
np.linspace(2,10,num=7)#başlangıç ve bitiş değeri aralığında belirtilen miktarda eşit aralık 

array([ 2.        ,  3.33333333,  4.66666667,  6.        ,  7.33333333,
        8.66666667, 10.        ])

In [49]:
np.random.randint(0,10,(5,2))#0-10 aralığında 5*2 rastgele sayıdan oluşan 2 boyutlu dizi

array([[8, 1],
       [2, 6],
       [5, 7],
       [2, 7],
       [0, 0]])

**diziler ile ilgili işlemler**

In [54]:
#dizilerin eleman sayısını öğrenmek için shape kullanılır
dizi=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
dizi.shape

(3, 4)

In [56]:
#ndim dizi boyutunu öğrenmek için kullanılır
dizi.ndim

2

In [58]:
#size dizideki toplam eleman sayısını gösteriri
dizi.size

12

In [60]:
dizi.itemsize #dizideki her bir elemanın bayt cinsinden değerini verir

4

In [69]:
#5 satır 7 sütün olacak şekilde rastgele sayılardan oluşan int türünde bir dizi oluştur
random_array = np.random.randint(0, 10, size=(5, 7))
print(random_array)

[[6 6 4 6 9 0 6]
 [4 7 8 9 0 0 9]
 [2 9 1 0 2 4 8]
 [3 9 9 6 6 1 5]
 [0 1 1 5 2 4 5]]
